### ISSUE TITLE
Ability to hide a wallet

### ISSUE THREAD

**Issue by SpiritOTHawk** [peercoin/peercoin_flutter#258]
Add ability to delete a wallet

**Comment by willyfromtheblock** [comment]
Thank you for your suggestion, @SpiritOTHawk. However, we have decided not to implement the ability to delete wallets. This is because it could cause disruptions in the address derivation process. The order of wallets is important for deterministic address generation, and removing a wallet could potentially disrupt this order. We appreciate your understanding and encourage you to continue sharing your ideas for improving our platform.

**Comment by ihavenoface** [comment]
The ability to hide / archive wallets would be a good compromise.
